ClusterName={{ slurm_cluster_name }}
SlurmctldHost={{ slurm_controller }}

AuthType=auth/munge
SlurmUser=slurm

NodeName={{ slurm_node }} CPUs={{ slurm_cpus }} Boards=1 SocketsPerBoard=1 CoresPerSocket={{ slurm_cores_per_socket }} ThreadsPerCore={{ slurm_threads_per_core }} RealMemory={{ slurm_real_memory }} State=UNKNOWN

PartitionName=debug Nodes={{ slurm_node }} Default=YES MaxTime=INFINITE State=UP

SelectType=select/cons_tres
SelectTypeParameters=CR_Core

SlurmctldPidFile=/run/slurmctld.pid
SlurmdPidFile=/run/slurmd.pid

SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log

StateSaveLocation=/var/lib/slurm/slurmctld
SlurmdSpoolDir=/var/lib/slurm/slurmd

SlurmctldTimeout=120
SlurmdTimeout=300
ReturnToService=2

ProctrackType=proctrack/linuxproc
TaskPlugin=task/none

JobCompType=jobcomp/none
